- name: Deploy to AKS
  hosts: localhost
  connection: local

  vars:
    resource_group: "tp4-k8s-rg"
    aks_cluster_name: "tp4-k8s-cluster"

  tasks:
    - name: Azure login (Service Principal)
      command: >
        az login --service-principal
        -u {{ az_client_id }}
        -p {{ az_client_secret }}
        --tenant {{ az_tenant_id }}

    - name: Get AKS credentials
      command: >
        az aks get-credentials
        --resource-group {{ resource_group }}
        --name {{ aks_cluster_name }}
        --overwrite-existing

    - name: Clean old temp k8s folder
      file:
        path: /tmp/k8s
        state: absent

    - name: Create temp k8s folder
      file:
        path: /tmp/k8s
        state: directory

    - name: Copy k8s manifests folder to temp
      copy:
        src: "{{ playbook_dir }}/../k8s/"
        dest: /tmp/k8s/

    - name: Debug copied files
      command: ls -R /tmp/k8s

    - name: Replace image placeholder in deployment manifest
      replace:
        path: /tmp/k8s/deployment.yml
        regexp: 'DOCKER_IMAGE_PLACEHOLDER'
        replace: "{{ docker_image }}"

    - name: Apply Namespace first
      command: kubectl apply -f /tmp/k8s/namespace.yml

    - name: Apply remaining Kubernetes manifests
      command: kubectl apply -f /tmp/k8s/

    - name: Wait for deployment to be ready
      command: kubectl rollout status deployment/backend-deployment -n tp4-devops --timeout=120s

    - name: Wait for Ingress IP to be assigned
      command: kubectl get ingress tp4-devops-ingress -n tp4-devops -o jsonpath='{.status.loadBalancer.ingress[0].ip}'
      register: ingress_ip
      retries: 15
      delay: 20
      until: ingress_ip.stdout != ""

    - name: Show Ingress IP
      debug:
        msg: "Ingress IP is: {{ ingress_ip.stdout }}"

    - name: Smoke Test - GET /api
      uri:
        url: "http://{{ ingress_ip.stdout }}/api"
        method: GET
        status_code: 200
      retries: 5
      delay: 10
      register: smoke_result
      until: smoke_result.status == 200


    - name: Smoke Test PASSED
      debug:
        msg: "Smoke Test PASSED ✅ - Response: {{ smoke_result.json | default(smoke_result.content) }}"